### ISSUE TITLE
pycon.cz

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/cz.pycon.org-2015#13]
We should write to owner of pycon.cz and ask him for redirect. @encukou should know more details.

**Comment by tricoder42** [comment]
That's a good idea :bulb: @encukou knows him personally?

**Comment by encukou** [comment]
@tricoder42, I don't know him personally but I can ask. I'd rather do it after we actually have something on cz.pycon.org, though.

**Comment by tricoder42** [comment]
@encukou http://cz.pycon.org is already created in #3. Right now it points to http://pycon.pyvec.org. Once I create EC2 instance and will have IP address, we can create A, AAAA records for `pycon` subdomain.

**Comment by encukou** [comment]
Sounds good.

@radeksimko, are you the Radek that owns the pycon.cz domain? Could you redirect it to cz.pycon.org, once we get that going?

**Comment by radeksimko** [comment]
@encukou Sure thing, excited to see Pycon coming up in Czech Republic! :+1: :smiley:
I'd be glad to help any way I can w/ the organisation too.

@tricoder42 Do you guys plan to keep the infrastructure code versioned somewhere too?

Since I see you guys decided to use AWS, I'd suggest you create a Route53 hosted zone and send me given NS records which I'll set up, so you can control the whole domain from Route 53 - ideally transparently (= Infrastructure as a code).

If you guys decide using https://terraform.io/ I can offer some help in setting things up.
Feel free to ping me via Hangout using my Github email.

**Comment by tricoder42** [comment]
@radeksimko Thank you! :+1: 

At the moment I don't know how to version infrastructure. I guess Terraform is the tool for that, right? I'm interested in it, but I need to read docs first.

I've created hosted zone in AWS Route53, NS records are:

```
ns-638.awsdns-15.net. 
ns-413.awsdns-51.com. 
ns-1773.awsdns-29.co.uk. 
ns-1402.awsdns-47.org.
```

Thank you for your cooperation, you're awesome :rocket: :tada:

**Comment by radeksimko** [comment]
> I guess Terraform is the tool for that, right?

I think you can do it via [Puppet](https://github.com/puppetlabs/puppetlabs-aws), [Ansible](http://docs.ansible.com/guide_aws.html), [CloudFormation](http://aws.amazon.com/cloudformation/) and more, I just do prefer Terraform from a couple of reasons. I can explain the reasons if you're interested, I just didn't feel this issue is the right place to do so.

**Comment by radeksimko** [comment]
NS records should be set now, it may take up to 24hrs to propagate.

**Comment by tricoder42** [comment]
Awesome, thank you. I'll handle the rest.

I'll also investigate CloudFormation or Ansible and see what I can do.

**Comment by pixelfields** [comment]
@tricoder42 If you want I can help you with this. I have a lot working experiences with automated deployment through SaltStack and CloudFormation in the AWS environment.

**Comment by tricoder42** [comment]
@pixelfields Sure, that would be helpful. I would rather use [Ansible](http://docs.ansible.com/cloudformation_module.html) instead of SaltStack, but in theory the process will be the same.

**Comment by tricoder42** [comment]
I've found Python library to generate CloudFormation templates: https://github.com/cloudtools/troposphere

**Comment by tricoder42** [comment]
It's up!
