### ISSUE TITLE
Find a dedicated person who will talk to sponsors

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/cz.pycon.org-2015#16]
From our experience, talking to sponsors, negotiating, signing contracts etc. can take unexpected amount of time in some cases and it can become a tiring experience. I think we should find someone who will champion this. Also, the negotiation shouldn't start later than on September.

**Comment by tricoder42** [comment]
:+1:

**Comment by tricoder42** [comment]
Do you have any idea, who would be the right person? Or do you know someone, who could know somebody?

**Comment by honzajavorek** [comment]
No. I'd ask on Django Girls / PyLadies / django-cs / py.cz, etc. mailinglists.

**Comment by lspdv** [comment]
Hi, as I have already promised before on Pyvo meeting to Kuba Vysoký - I could be a "little helper" for Pycon. Since I can not help you with things around Python I can offer you help with organising event (so  I hear on  commands like : find supplier, go there, bring this, arrange it, sell it, buy it, negotiate with them etc.

I am still too young to know everything, but I am learning fast and I know the right people for mentoring. I work on few projects relating to the organization of the big events already. I work for Institut městského rozvoje, VIZE PRAHA 10 and Mocvelkarodina.cz

I'd like to help you, because I am grateful to Python people who organized DjangoGirls and PyLadies.

**Comment by honzajavorek** [comment]
Hi Veronika, I suspect Tomas is on vacation and that's reason why he's not
replying, but your volunteering and will to help us with this is
super-awesome and we appreciate it very much! We would be extremely glad if
you join us!

**Comment by tricoder42** [comment]
@lspdv Hi Veronika :rose:, sorry for such a late response. I'm not on vacation, but extremely busy at the moment. The notification just slipped through my mailbox and I forgot about it :disappointed: 

I would be very happy if you could help us. At the moment, I need to setup communication channels (in progress in #19) so we can organize things together. Then we'll decide what needs to be done and when.

The first deadline is 1st August, when I want to publish Call for papers :speech_balloon:. It basically means we need to setup website (Django project).

I'll definitely contact you soon! :rocket:

**Comment by lspdv** [comment]
Hi, thanks for answer :+1: let me know, whenever you want, I sent you email with contact before few mins! :-)

**Comment by tricoder42** [comment]
This will be mostly done by me with help of @thatdocslady

**Comment by honzajavorek** [comment]
Mind that if accounting goes through Pyvec, you need to get contracts and
other paperwork signed by its representatives (see http://pyvec.org/o-nas/
) in case sponsors require a contract. It is not difficult, it's just
time-consuming and tiring, because it involves coordination of random,
randomly organized people.

**Comment by tricoder42** [comment]
I'm aware of that. I'm in contact with people from Pyvec, we'll discuss details when I came back from vacation.

**Comment by honzajavorek** [comment]
:+1: superb
