### ISSUE TITLE
Design logo

### ISSUE THREAD

**Issue by tricoder42** [pyvec/cz.pycon.org-2015#21]
# Inspiration
## With national flags
- http://pl.pycon.org/2015/index.html
- http://www.pycon.se
## Without national flags
- https://ep2015.europython.eu/en/
- https://www.pycon.it/en/
- https://us.pycon.org/2014/
## Seems without custom logo at all :)
- https://nzpug.org
- http://www.pyconuk.org

**Comment by lspdv** [comment]
I really like  https://ep2015.europython.eu/en/ ....looks very sophisticated and unique. Let's do something NEW unique and colorful also...

logo http://www.pyconuk.org/ - looks a bit perverse to me?! I couldn't find python among those foot, kitty....and MyLittlePony???!

**Comment by tricoder42** [comment]
@honzajavorek likes EuroPython 2015 as well.

PyCon UK seems like Monty Python graphics and the crown is nice :) Still, it's too chaotic for me...

**Comment by lspdv** [comment]
I know Monty Python pretty well...and it is good idea....but I had no association with Monty Python before you told me - so maybe designer's fault maybe I am outsider :-) but it is chaotic :-)

Jesus :-)

**Comment by encukou** [comment]
Well, we do have a common design theme for Pyvec. Let's get @honzajavorek to scribble a snake waving a Czech flag. I think it would be perfect for the Early Adopters edition :)

**Comment by honzajavorek** [comment]
Yes, we agreed on sth like that on Slack :) I just need some time as I'm leaving for vacation in couple of days. If I won't get back to this myself, remind me about this in half of August, pls.

**Comment by tricoder42** [comment]
cc @thatdocslady

**Comment by thatdocslady** [comment]
DRAGON WINGS! :D

**Comment by honzajavorek** [comment]
I'll try to come up with some proposals soon, just came back from vacation. If you have ideas for the theme, mascot, anything, let me know before I sit at the drawing table!

**Comment by calmrat** [comment]
Here's something @thedocslady and I were talking about recently

Standard Python double snake, but with a Brno dragon wings/crocodile twist
  http://www.brno.cz/en/tourist-leisure/history/brno-tales/the-brno-dragon/

Maybe the snake should be 'brno colors'? Black and Green? I don't actually
know if there are official brno colors though... maybe rather blue and
write (ie, Kometa ;)

Or ...

(Spilberg/skyline background)
PyCon Brno (or is it PyCon CZ?)  (mid)
(Brno PySnakes logo) (bottom)

Maybe add some colorful fireworks to play off of the *IGNIS BRUNENSIS
http://www.ignisbrunensis.cz/starobrno-ignis-brunensis--558.html *fireworks
events that happen in Brno.

Or skull and cross... ;-)
http://www.gotobrno.cz/en/the-ossuary-of-st-james-church

Or some play off of
- the mammoths and sabre-toothed tigers at the exhibition in the Anthropos
  Pavillion http://www.gotobrno.cz/en/anthropos-pavilion
- the amazing brno "clock" http://www.gotobrno.cz/en/brno-clock-sculpture
- the observatory
- brno underground

-Chris

**Comment by honzajavorek** [comment]
Brno colors are red and white (see logo, coat of arms, official flag, etc.). However, red and white is rather colliding with nearby PyCon PL identity.

Snake with a twist of dragon is nice idea! :dragon_face:  I see you thought of something which could be called rather "PyCon Brno" than "PyCon CZ". Not sure whether it's the best way to approach this if we want this to be all-country effort. I'm afraid if we theme the conference as Brno-ish too much, the others will say "okay, so let the folks from Brno organize it and let's just sign up as attendees and speakers" instead of "yeah, this is a product of efforts of all of us here". Maybe I'm just paranoid, feel free to comfort me :cat2: 

Also, what I see as a drawback is that the logo would be unusable in case PyCon CZ is organized in other city in the future. However, it doesn't need to be such a problem as it's easy to draw a new logo for every year and my drawing style would be a connecting aspect of all the years.

**Comment by thatdocslady** [comment]
Good point, maybe we should go with a global-Czech theme rather than a city-specific theme. +1

**Comment by encukou** [comment]
I think a city-specific logo for each PyCon CZ is not a bad idea. Especially if it means we can use a dragon :)

**Comment by calmrat** [comment]
Without a doubt, your points are valid. Again, I'm still 'onboarding' and
participating from the sidelines. Designing for PyCon CZ makes much more
sense. With that in mind...

CZ is known well for partying and other such related activities... :-)
probably want to stay away from that though. Maybe some beer bubbles could
work... I mean... if we're honest with ourselves...

Well, to start (but not very good idea, i imagine) double snakes with the
cz flag colors (red, white, blue) with the part of the flag where the
colors all meet < being centered on the snakes...

Or double snakes with czech lion heads... tongue sticking out. Or snakes
with golden czech crown.

-Chris

**Comment by thatdocslady** [comment]
I'd rather keep alcohol out of official logos, if that's alright, because obvious reasons.

**Comment by rkuska** [comment]
:+1: for the dragon idea :-) (even europython2015 used colors specific for basque region in their logo)

**Comment by honzajavorek** [comment]
> I'd rather keep alcohol out of official logos, if that's alright, because obvious reasons.

:+1:

**Comment by honzajavorek** [comment]
I'm having hard time to get to this, but I did not forget about it. Feel
free to poke me to add urgency/motivation.

**Comment by honzajavorek** [comment]
Inspiration from other Python conferences (in my opinion, the best logo ideas I've seen after clicking through http://www.pycon.org/):

![](https://ep2015.europython.eu/static/p6/images/europython-2015-logo-white-bg.png)

![](http://www.pycon.se/assets/images/logo.png)

![](http://www.pycon.kr/2015/static/image/pyconkr-badge.png)

![](http://www.pyconuk.org/img/pycon.png)

![](http://pycon.ru/2015/img/new_logo.png)

Basically, the logo is not a big deal. From designer's point of view, most of PyCon logos are terrible, worldwide. So at least for this year, under pressure of time, I think we're good to go with something "good enough".

**Comment by honzajavorek** [comment]
Okay, this is my proposal. It's not anything super-awesome, but I spent quite a lot of time with it and I'm out of ideas. I liked this one the most.

![python-logo-inkscape4](https://cloud.githubusercontent.com/assets/283441/9429494/1b7ec5fc-49d2-11e5-8e7a-315d8feb4ebf.png)

### Explanation
- It features Czech colors, it is simple and yet it doesn't look completely stupid and generic.
- It _should_ look like if drawn by hand, so it sort of follows the style of [other Czech Python community graphics](https://github.com/pyvec/resources/tree/master/Design).
- I was able to create it in Inkscape and save as SVG.
- Don't ask me how inverted version looks like. I don't know.

### Font
- Amatic
  - http://www.fontsquirrel.com/fonts/amatic
  - https://www.google.com/fonts/specimen/Amatic+SC

**Comment by sYnfo** [comment]
Personally, I think that looks really good overall!

**Comment by honzajavorek** [comment]
Adding one more:

![python-logo-inkscape5](https://cloud.githubusercontent.com/assets/283441/9429958/c46898a4-49e2-11e5-9fdd-247b3880a4c4.png)

### Explanation
- It features Czech colors.
- It features Czech/Bohemian lion with two tails in shield-shaped outline. Coincidentally the two tails are also two pythons. It is basically a childish parody to [Lesser coat of arms of the Czech Republic](https://en.wikipedia.org/wiki/Coat_of_arms_of_the_Czech_Republic#/media/File:Small_coat_of_arms_of_the_Czech_Republic.svg).
- Shield-like logo also refers to long history and rich medieval background of Czech lands. 
- It _is_ drawn by _my_ hand, so it follows the style of [other Czech Python community graphics](https://github.com/pyvec/resources/tree/master/Design).
- I was able to create it in Inkscape and save as SVG.
- Don't ask me how inverted version looks like. I don't know. Also don't ask me how to make a favicon from this.

### Font
- Amatic
  - http://www.fontsquirrel.com/fonts/amatic
  - https://www.google.com/fonts/specimen/Amatic+SC

**Comment by honzajavorek** [comment]
Other option - to use both. The second as main logo (homepage, t-shirt, ...) and the Python logo outlined in Czech colors from the first proposal as an alternative for smaller/simpler applications (favicon, Twitter, t-shirt sleeves, etc.).

**Comment by thatdocslady** [comment]
I like both, except for the part where the snakes are growing out of the lion's butt ;) but if you can fix that somehow, it can be a great combo for prints and web. 

Awesome sauce!!!

**Comment by netman92** [comment]
I :+1: the first one.

**Comment by pksunkara** [comment]
@honzajavorek Since you asked, I like the lion but not it's tails.

**Comment by honzajavorek** [comment]
> the snakes are growing out of the lion's butt

Well, that's the main idea - Czech coat of arms features double-tailed lion. The drawing puts the lion together with Python's snakes. The problem is that the fact about double-tailed lion is not known to people out of Czech context, so the international audience will probably just see exactly what you wrote, i.e. two snakes growing out of the lion's butt.

**Comment by JackuB** [comment]
@honzajavorek I like first one, maybe you could try more variants of it - with color fill, text underneath, pycon on left and 2015 on right etc.

@pksunkara [double tailed lion](https://en.wikipedia.org/wiki/Coat_of_arms_of_the_Czech_Republic) for reference. That tail looks strange if you are not accustomed seeing this everywhere I guess.

**Comment by pksunkara** [comment]
@JackuB I understood the reference. But in that particular drawing, it looks weird. I was asking Javor to change it a bit.

**Comment by starenka** [comment]
The first one looks nice. Nevertheless I personally like the idea of the second one more. It has been exploited a lot of times but for me still has something in it:
- https://www.avu.cz/sites/default/files/editor/logoczneg.jpg (academy of fine arts prague)
- http://intranet.cvut.cz/pracoviste/odbor-vnejsich-vztahu/obrazky/logo/cvut-logo-bw-600.png (czech technical university prague)
- more... (I can see Honza likes this magazine too, as it had similar cover recently ;) http://www.respekt.cz/tydenik/2015/34 )

I realize it maybe looks a bit weird for somebody outside of cz/sk. Btw the idea of Pycon CS has been scratched as I see now? If not I somehow see a logo with two countries separated but still tied together again with a snake a cool idea ;)

**Comment by Naomak** [comment]
I prefer the first one

**Comment by honzajavorek** [comment]
To address various comments:
- "But in that particular drawing, it looks weird." @pksunkara I think I'd need more guidance. Can you be specific? What do you think is the root problem? E.g. does it even look like a tail?
- "you could try more variants of it - with color fill, text underneath, pycon on left and 2015 on right etc" @JackuB I tried. They're not public, but mostly they looked strange. Color fills seemed to be too aggressive and various color combinations seemed to resemble different countries (one snake red and one blue = pepsi / Korea, red snakes with blue/white outline = Norway, ...)
- @starenka hah, I have exactly this issue of the magazine at home, but since my GF bought it and it's usually folded and left behind with other pages at the top, I did not even realize what the cover drawing is! :camel: 
- To all: Regarding PyCon CS, I think the idea is not scratched for ever, but just for now to simplify organization of the first edition. Similar to other conferences, I have no problem with having new graphics/logo for every year. We don't need to design anything eternal here now, we can throw it away next year.

My personal preference would be the second one as main logo. I just like it more - seems less boring to me than the first one. However, I take pretty seriously the issue with two tails being unrecognizable and confusing and I see this can be a stop sign for the proposal.

@thatdocslady @tricoder42 I think we need to come up with a process how to decide.

**Comment by sputnikus** [comment]
@honzajavorek First :+1:

**Comment by martinbilek** [comment]
Regarding "process how to decide", we are working on democratic voting/polling system (https://www.d21.me) which can be used for similar decision/voting issues. If you agree, we can prepare poll to test it... @honzajavorek @czervenka

**Comment by tricoder42** [comment]
Excellent job @honzajavorek ! :tada: :confetti_ball: :cocktail:

I like the first one as a conference logo, but I would put the second one (lion) on t-shirts... or something :) It looks like most of us like the first logo more than the second, so maybe we don't even have to setup voting?

**Comment by honzajavorek** [comment]
SVGs etc.: [pyvec/resources: Design/PyCon Logo/2015](https://github.com/pyvec/resources/tree/master/Design/PyCon%20Logo/2015) cc @tricoder42

**Comment by tricoder42** [comment]
Awesome, thank you very much! :tada: :confetti_ball: :dancer:
