### ISSUE TITLE
Venue

### ISSUE THREAD

**Issue by encukou** [pyvec/cz.pycon.org-2015#23]
- Brno, VUT FIT?
- Prague, ?
- ?

**Comment by encukou** [comment]
Mikey's crazy idea: rent Fléda for two days and do a Pycon there.

**Comment by tricoder42** [comment]
Have you ever been to Fleda? I believe there are dozens of more interesting venues in Brno. I don't know if there's some hidden room, but the main stage is more suitable for rock concerts that conferences.

My list is:
- VUT FIT is the easiest and preferred choice. Everything is setup, A/V, Wifi, seating and projection.
- MU FI is another option with similar equipment.
- Impact Hub would be also interesting choice, but with a little bit of more work
- Scala Cinema is romantic, but it would require quiet lot of work to turn it into conference venue
- Mahenovo Theatre, Sono Music Club, BVV are nice venues, but very expensive to begin with

If you come up with any impressive argument why Fleda could be interesting venue, we can consider it and call them...

**Comment by honzajavorek** [comment]
I wouldn't put the idea aside right away, although it's quite crazy, yes (however, it was presented as crazy, so that's all right). I've been to Fleda for a theatre and the whole place was filled by quite a number of seats for audience, maybe also leveled if I recall right (long time ago).

**Comment by honzajavorek** [comment]
If Scala is considered, why Kino Art is not, by the way?

**Comment by tricoder42** [comment]
It is from now! :)

**Comment by encukou** [comment]
Industra?

**Comment by thatdocslady** [comment]
Pros for Fleda:
- Space, equipment, food, drinks, room blocks all in the same place (one-stop-shop)
- Conf sessions and party at the same location can make for better total price
- Close to center, on tram / night bus route
- Close to Avanti and Continental for different visitor accommodation requirements

**Comment by calmrat** [comment]
I just got here... so maybe it's posted somewhere else already, but what the target size we're making the decision around? Is it for sure going to be in Brno? (Definitely a +1 to that idea!!!) Do we already have a target date?

RE: Fleda; -1 from me. It's not designed for conference events; it's quite grungy and would require additional logistics in terms of renting chairs and tables, at a minimum. Not sure about their support for projectors, how many separate, closed spaces there are/can be, etc. As @tricoder42 says, yea, there are definitely better places in Brno. @thatdocslady Having the party at the same place would also mean there is no downtime at the venue; I can imagine it'd be more of a challenge to set-up the party when people are still having talks, sprints, etc. I think separating event/social events is a good thing.

I hosted a conference of 130 people last February at MU FI and I'll say the staff there are very gracious. While it's not the most attractive place in Brno, it's certainly reasonable in terms of price and if timing can be negotiated, a reasonable option. Plus the student presence is a +.

I think it would make sense for folks who suggest a venue to also call the venue and ask for estimate pricing and availability. Just a suggestion though...

**Comment by thatdocslady** [comment]
@kejbaly2 unfortunately I can't communicate with venues directly because Engrish, so @tricoder42 has graciously agreed to take that on. I am not particularly attached to Fleda, but I feel that we don't have to go with the uni route, there are lots of options in Brno (as you said), and having a place with its own personality contributes a lot to the atmosphere. AFAIK the target capacity is 200-300ppl, but I'm sure one of the BDFLs can attest to that.

**Comment by thatdocslady** [comment]
Also @kejbaly2 - NIIICCCCCEEEEEEE :smiling_imp:

**Comment by tricoder42** [comment]
Yes, my original target was 150 people, I guess ~250 people might be optimal. We should count with Django Girls (~40-50), I would really like to invite them for free after they complete the workshop.

**Comment by calmrat** [comment]
I hear Impact Hub Brno is an amazing venue, recently a Docker event for 150 or so was run there, but available more or less only on weekends. I'll try to get price details.

RE: MU FI, I'm going to put out the estimate price based on previous experience between 200czk for the smaller rooms (20p) to 1000czk (~180) per hour. Clearly, it'd be simpler to run the event when school's out for the summer or spring than while during the regular school year.

Honestly though, like @thatdocslady if there would be a reasonable priced place that's not a uni, +1 to that. 

I can only imagine it's cheaper in Brno than Prague on average. Do others have any experience that says otherwise?

I'm sure this isn't the place to ask... but i will anyway. Will participants be expected to pay for a ticket or will the conf be free? If free, is there a budget coming from somewhere to pay for venue, etc? Clearly, this will be important when deciding too... :) Telling me to RTFM is a valid response, if this info is doc'd somewhere already. 

/me goes to read the other open issues and remaining docs in this repo now...

**Comment by tricoder42** [comment]
Impact Hub is nice, but open-space is for 200 people only. It could be good place for Django Girls workshop though.

The conference will be definitely paid. The draft of budget is in google drive. It's semi-private, you can find link to it on slack. I've already sent you an invite.

**Comment by calmrat** [comment]
Good point. If you think we'll hit more than 200 then it'd be an issue.

**Comment by calmrat** [comment]
OK, i have received a link to the draft budget. And I see the answer is YES, expectation is participants will pay for the pleasure of rockin' it pycon cz. Nice. Thanks. I'll try to track down a price estimate for fleda, even if it would be just  for the evening social event. 

Kino Art / Scala could be interesting... anyone have specs on those venues for comparison?

**Comment by tricoder42** [comment]
Document comparing venues is also on Slack (room #venue)

**Comment by calmrat** [comment]
got it; checking it out now. Thanks.

**Comment by tricoder42** [comment]
Brno (FIT)
